* Overview

This is the source code for the javajing.com website. 

The site is written in emacs using org-mode. The *.org
files are then processed to create the html/css/js website. Then,
those files are processed using Jekyll to create the final site.

The java webapp inside this project includes some tools to help
publishing the site from org-mode to the web.

* Steps to create the website

- First, run scripts/stage.sh to move files into the jekyll directory
  structure.

- Next, use org-mode to convert show-notes.org files into html posts.
  Eval scripts/org-project.el and then run `org-publish-project
  javajing`.

- Remember to generate thumbnail images for episode poster
  #+begin_src sh
  cd videos/<episode-dir>
  ../../script/resize-images.sh episodeXX-poster.png
  mv *.png ../../site/src/main/webapp/jekyll/images/javajing
  #+end_src

- Use Jekyll to publish the final site. 
  #+BEGIN_SRC sh
rvm use ruby-1.9.2-p180
rvm use gemset jekyll
./script/publish.sh
  #+END_SRC

- Run deploy.sh to push static html site generated from jekyll to
  production server


