Java servlet containers such as weblogic, jetty, tomcat, etc run on
various ports. For example, tomcat listens on port 8080 by default.
It's often convenient to proxy servlets and java apps over
port 80. This is useful for several reasons: 

- End users don't need to remember port numbers to access production
- It's also a good practice from security perspective. Rather than
  opening various ports, you can lock down everything and then allow
  access over port 80 and/or 443.
- Saves time to your dev environment to use port 80 so you can ensure
  the app uses portable urls

Here's a demo of how to use Apache mod_proxy to set this up inside
your development environment. 

* Steps

** Verify apache proxy and rewrite modules are enabled

Here's how you can check whether the modules are enabled: 

#+SRC_BEGIN
# might need to set APACHE_RUN_USER environment variable using this:
. /etc/apache2/envvars

apache2 -l # list of compiled in modules
apache2 -M # list of dynamically loaded modules

apache2 -M | grep proxy

apache2 -M | grep rewrite

#+SRC_END

In Apache2, use the following commands to enable the modules

#+SRC_BEGIN
a2enmod proxy
a2enmod proxy_http
a2enmod rewrite
#+SRC_END

** Configure new vhost

Create app-name.conf file under /etc/apache2/sites-available

<VirtualHost *:80>
    ServerAdmin upgradingdave@gmail.com
    ServerName javajing.com
    DocumentRoot /home/dparoulek/projects/javajing/apache-proxy/simple-webapp/src/main/webapp
    ErrorLog "logs/javajing-error"
    CustomLog "logs/javajing-access_log" common

    <Location />
      Order allow,deny
      Allow from all
    </Location>

    ProxyRequests On
    RewriteEngine On

    RewriteRule ^/$ http://localhost:8080/simple-webapp [P]
    RewriteRule ^/(.+)$ http://localhost:8080/simple-webapp/$1 [P]

</VirtualHost>

** enable new vhost

#+SRC_BEGIN
sudo a2ensite <app-name>.conf
#+SRC_END

** check configs

#+SRC_BEGIN
sudo apache2ctl configtest
#+SRC_END

** Set up subdomain

I like to add to local hosts file. 

** restart apache and test

* Links

JSTL JavaDoc
http://docs.oracle.com/javaee/5/jstl/1.1/docs/tlddocs/

XAMMP
http://www.apachefriends.org/en/xampp.html






