#+BEGIN_HTML
---
layout: post
title: Dependency "H-E-Double Toothpicks"
episode: 15
summary: Dependency version conflicts can get real ugly. Maven dependency:tree and enforcer:enforce to the rescue!
video: dependency-hell.mp4
---
#+END_HTML

* Dependency "H - E - Double Toothpicks"

  Find a copy of the companion source code for this episode here:

  https://github.com/upgradingdave/javajing/tree/master/dependency-hell

  In case you're viewing this in github, please find the Episode here:

  http://javajing.com/2012/09/17/dependency-hell.html

** Troubleshooting tips

   - Be suspicious about possible Dependency Conflicts issues when
     using old version of libraries, or when using new bleeding
     leading edge libraries

   - Use `mvn dependency:tree` to see recursive list of all
     dependencies as well as dependencies' dependencies and so on

   - Try excluding suspicious dependencies using the maven "exclusion"
     feature. 

** Maven Enforcer Plugin

   Once you've pinpointed the problem dependency, use the Maven
   Enforcer Plugin to make sure it never sneaks back into your projects!

#+begin_src xml
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-enforcer-plugin</artifactId>
        <version>1.0.1</version>
        <executions>
          <execution>
            <id>enforce-banned-dependencies</id>
            <goals>
              <goal>enforce</goal>
            </goals>
            <configuration>
              <rules>
                <!-- Doesn't exclude on its own, but does check that it is excluded -->
                <bannedDependencies>
                  <excludes>
                    <exclude>xerces:xerces:1.4.4</exclude>
                  </excludes>
                </bannedDependencies>
              </rules>
              <fail>true</fail>
            </configuration>
          </execution>
        </excecutions>
      </plugin>
#+end_src   

** Links

   - Cool image of all linux dependencies used as title screen ::
        http://disfunksioneel.blogspot.com/2011/04/linux-software-dependencies.html

   - Maven dependency plugin ::
        http://maven.apache.org/plugins/maven-dependency-plugin/

   - Maven enforcer plugin ::
        http://maven.apache.org/plugins/maven-enforcer-plugin/

